"""add_geoip_fields_to_asset

Revision ID: d9d72524fbdb
Revises: 6664083759b2
Create Date: 2026-03-24 13:19:00.127320

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9d72524fbdb'
down_revision: Union[str, None] = '6664083759b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets', sa.Column('country', sa.String(length=100), nullable=True))
    op.add_column('assets', sa.Column('isp', sa.String(length=100), nullable=True))
    op.add_column('assets', sa.Column('asn', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assets', 'asn')
    op.drop_column('assets', 'isp')
    op.drop_column('assets', 'country')
    # ### end Alembic commands ###
